### Problem solvong with Numpy

1. Write a function, foo_1, that takes a NumPy array `arr` and returns the indices of the elements that are closest to a given target. If target is not in the given array, it should return ‘no item found’

In [2]:
import numpy as np

In [115]:
def foo_1(a, target):
    numpy_array = np.array(a)
    result_arr = []
    arr = abs(target - numpy_array)
    if len(np.where(numpy_array == target)[0]) == 0:
        print("no item found")
    else:
        for i in np.arange(0, max(arr)+1):
            result_arr = np.append(result_arr, np.where(arr == i))
        print(result_arr.astype(int))

In [116]:
foo_1([3, 8, 7, 7, 7, 7, 7, 8, 7, 10], 7)

[2 3 4 5 6 8 1 7 9 0]


In [117]:
foo_1([3, 8, 7, 7, 7, 7, 7, 8, 7, 10], 11)

no item found


2. Write a user defined function foo_2 that takes a  2,3 dim NumPy array arr and returns a new n-1 dim array, where each element is replaced by the count of non-zero elements wrt axis.

In [58]:
def is_positive(a):
    counter = 0
    for i in a:
        if i>0:
            counter+=1
    return counter

In [59]:
def find_count(arr1, axis_value):
    print(np.apply_along_axis(is_positive,axis=axis_value, arr=arr1))

In [60]:
arr = np.array([[1, 2, 3, 4],
                [0, 5, 0, 0],
                [2, 0, 1, 0]])
find_count(arr, 0)

[2 2 2 1]


In [194]:
find_count(arr, 1)

[4 1 2]


In [196]:
arr1 = np.array([[[1, 2, 3, 4],
                 [0, 5, 0, 0],
                 [2, 0, 1, 0]],
                 
                 [[2, 0, 1, 0],
                 [0, 5, 0, 0],
                 [1, 2, 3, 4]]])
find_count(arr1, 0)

[[2 1 2 1]
 [0 2 0 0]
 [2 1 2 1]]


In [197]:
find_count(arr1, 1)

[[2 2 2 1]
 [2 2 2 1]]


In [198]:
find_count(arr1, 2)

[[4 1 2]
 [2 1 4]]


3
1. You are given a 2D NumPy array of data representing student scores. Each row represents a student, and each column represents a subject. Extract the scores of all students who scored above 90 in at least one subject. Provide the resulting array.

In [334]:
x = np.array([[85, 89, 88],
             [78, 89, 94],
             [91, 87, 90],
             [87, 95, 84]])

In [365]:
def func_marks(a):
    z = np.array([0,0,0])
    for i in a:
        if len(np.where(i > 90)[0]) > 0:
            z = np.vstack((z, i))
    print(z[1:])

In [366]:
func_marks(x)

[[78 89 94]
 [91 87 90]
 [87 95 84]]


2. You are provided with a 2D NumPy array of data representing sales data for different products. Each row corresponds to a product, and each column represents the monthly sales for a specific month. Calculate the following statistics for each product: mean, median, standard deviation, and the month with the highest sales.

In [521]:
x = np.array([[120, 150, 130, 110],
              [200, 180, 220, 250],
              [90, 100, 95, 110],
              [300, 280, 320, 340]])

In [522]:
def find_index(a):
    for i in enumerate(x):
        if np.all(i[1] == a):
            return i[0] + 1

In [523]:
def calculate(a):
    print(f'Product: {find_index(a)}:', end='\n')
    print(f'Mean: {np.mean(a)}', end='\n')
    print(f'Median: {np.median(a)}', end='\n')
    print(f'Standard Deviation: {np.std(a)}', end='\n')
    print(f'Month with Highest Sale: {np.where(a == np.max(a))[0][0] + 1}', end='\n\n')

In [524]:
x = np.apply_along_axis(calculate, axis=1, arr=x)

Product: 1:
Mean: 127.5
Median: 125.0
Standard Deviation: 14.79019945774904
Month with Highest Sale: 2

Product: 2:
Mean: 212.5
Median: 210.0
Standard Deviation: 25.8602010819715
Month with Highest Sale: 4

Product: 3:
Mean: 98.75
Median: 97.5
Standard Deviation: 7.39509972887452
Month with Highest Sale: 4

Product: 4:
Mean: 310.0
Median: 310.0
Standard Deviation: 22.360679774997898
Month with Highest Sale: 4



3. Create a NumPy array of size 1000 with random integers between 1 and 100. Then, use NumPy functions to find the top 10 most frequently occurring values in the array.

In [54]:
zz = np.random.randint(1,100,1000)
values, count = np.unique(zz, return_counts=True)

In [56]:
sorted_indices = np.argsort(-count)[:10]

In [57]:
for i in sorted_indices:
    print(f'{values[i]} occured {count[i]} times')

97 occured 18 times
24 occured 18 times
40 occured 17 times
55 occured 16 times
42 occured 16 times
86 occured 16 times
15 occured 16 times
74 occured 15 times
73 occured 15 times
14 occured 15 times
